### ISSUE TITLE
Great library!

### ISSUE THREAD

**Issue by brendannee** [cal-itp/gtfs-service-area#3]
This library is very useful in creating buffers and polygons around service areas which is something I needed to do recently. 

Inspired by gtfs-service-area, I added support for these kinds of outputs to the gtfs-to-geojson library  https://github.com/BlinkTagInc/gtfs-to-geojson/.

I recently switched gtfs-to-geojson to use SQLite instead of MongoDB so the initial setup is a little easier than it used to be.  I also added support so that you can get geojson for an entire agency or each individual route.

I added `thekaveman Kegan Maher` as a contributor to gtfs-to-geojson.

Feedback or suggestions on gtfs-to-geojson is always welcome.

**Comment by thekaveman** [comment]
Thanks @brendannee! Glad you found this useful; obviously it wouldn't have been possible without `gtfs-to-geojson` so thank you for that as well!

I think it's great this functionality has been incorporated there (and major props for moving away from the MongoDB requirement!!!). We have a few projects coming up that may need to make use of some service coverage data, I'll be sure to check out `gtfs-to-geojson` and provide any feedback.
